# Generated by Django 3.1 on 2020-08-08 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('userid', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='user id')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='templates/IMAGE/avatar/%Y/%m/%d/', verbose_name='avatar')),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('0', 'Administrator'), ('1', 'Normal')], default='Normal', max_length=30, verbose_name='role')),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='Male', max_length=3, verbose_name='gender')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('remember', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
