"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import sys
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent
 
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))#新增


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5*^-4)-&9@l(=any3__82!(!uzbil*!gl)bh-4gn&x__n^ozpx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.userSystem',
    #'werkzeug_debugger_runserver',
    #'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates/HTML5/','userSystem'),
              os.path.join(BASE_DIR, 'templates/HTML5/','documentManagement'),
              os.path.join(BASE_DIR, 'templates/HTML5/','library'),
              #os.path.join(BASE_DIR, 'templates/HTML5/','tools-Platform'),
              ] ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'djangodata',
        'USER': 'test',
        'PASSWORD': 'test..2020',
        'HOST': 'localhost',
        'PORT': 5432,
    }
}



#Session
#https://docs.djangoproject.com/en/3.1/search/?q=session

SESSION_ENGINE = 'django.contrib.sessions.backends.db'   # 引擎（默认）
    
#SESSION_COOKIE_NAME ＝ "sessionid"                       # Session的cookie保存在浏览器上时的key，即：sessionid＝随机字符串（默认）
#SESSION_COOKIE_PATH ＝ "/"                               # Session的cookie保存的路径（默认）
#SESSION_COOKIE_DOMAIN = None                             # Session的cookie保存的域名（默认）
#SESSION_COOKIE_SECURE = False                            # 是否Https传输cookie（默认）
#SESSION_COOKIE_HTTPONLY = True                           # 是否Session的cookie只支持http传输（默认）
#SESSION_COOKIE_AGE = 1209600                             # Session的cookie失效日期（2周）（默认）
#SESSION_EXPIRE_AT_BROWSER_CLOSE = False                  # 是否关闭浏览器使得Session过期（默认）
#SESSION_SAVE_EVERY_REQUEST = False                       # 是否每次请求都保存Session，默认修改之后才保存（默认）



AUTH_USER_MODEL = 'userSystem.MyUser'
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/template/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'templates/CSS/'),
    os.path.join(BASE_DIR,'templates/JS/'),
    os.path.join(BASE_DIR,'templates/IMAGE/'),
    os.path.join('E:/xlq/vscode/node_modules/mind-elixir/dist/'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media/')
